import Navbar from "@/components/Navbar";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
Navbar

const font = Poppins({
   subsets: ["latin"],
   weight : ['400','600']
   });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={font.className}>
        <div className="sticky top-0 backdrop-blur z-[999]">
          <Navbar />
        </div>
         
        {children}
        </body>
    </html>
  );
}
